name: GymPose data from YT artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0,6,12,18 * * *'

concurrency:
  group: gympose-artifact-to-data
  cancel-in-progress: false

jobs:
  run-gympose:
    permissions:
      actions: read
      contents: read
    uses: kioallan905124z/go/.github/workflows/gympose-data.yml@master
